Refactor paging#111
BYU-ODH/retabled pull request #114
Opened 2022-08-08 18:49 UTC by dalpal07

closes #111 

we should look at the functionality together and make sure you like it @WorldsEndless

2022-08-08 18:57 UTC, dalpal07 commented
also closes #109

2022-08-11 16:25 UTC, WorldsEndless requested changes

2022-08-11 16:25 UTC, WorldsEndless commented on src/retabled/internal.cljc
> +                                           (when (not= (:go-to-value @PAGING-INFO) "")
this should use `empty?` instead of checking for `""`

2022-08-11 17:45 UTC, dalpal07 commented
@WorldsEndless Issue is fixed

2022-08-11 17:47 UTC, WorldsEndless approved these changes

2022-08-11 17:47 UTC, merged