Update readme#23
BYU-ODH/retabled pull request #29
Opened 2022-06-15 18:57 UTC by dalpal07

Closes #23

2022-06-16 16:33 UTC, WorldsEndless requested changes

2022-06-16 16:33 UTC, WorldsEndless commented on README.org
> +	    [accountant.core :as accountant]))
accountant not needed in the readme

2022-06-16 18:26 UTC, dalpal07 commented
@WorldsEndless I have fixed the changes we talked about and committed that and pushed it to this branch. It is the most recent of the 5 commits.

2022-06-23 16:01 UTC, WorldsEndless approved these changes

2022-06-23 16:01 UTC, merged